import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
// import Link from 'next/link';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='light'>
      <body className={`${inter.className} relative min-h-screen px-4`}>
        <Providers>
          <Header />
          <main className='p-10 lg:w-[1200px] mx-auto mt-[5rem] bg-white dark:bg-gray-700 rounded-2xl shadow-xl mb-10'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
